export enum FieldTypeEnum {
  STRING = "STRING",
  NUMBER = "NUMBER",
  BOOLEAN = "BOOLEAN",
  DATE = "DATE",
  LIST_CONTENT = "LIST_CONTENT",
  TEMPLATE = "TEMPLATE",
  ANY = "ANY",
  ARRAY_STRING = "ARRAY_STRING"
}